In [2]:
import numpy as np
import pandas as pd
import datascience as ds

from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
from scipy import stats

In [3]:
#Part 1:
#Check Narrative in submission

In [4]:
#Part 2:
#Making the dataframes
stats = Table.read_table('stats.csv')
results = Table.read_table('results.csv')

In [78]:
stats

Team     | Player            | D.O.B      | Height | Weight | Position          | Season | Round | Date       | Score | Margin | WinLoss | Opposition | Venue     | Disposals | Kicks | Marks | Handballs | Goals | Behinds | Hitouts | Tackles | Rebound50s | Inside50s | Clearances | Clangers | FreesFor | FreesAgainst | BrownlowVotes | ContendedPossessions | UncontendedPossessions | ContestedMarks | MarksInside50 | OnePercenters | Bounces | GoalAssists | PercentPlayed
Adelaide | Atkins, Rory      | 1994-07-12 | 186    | 85     | Midfield          | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 14        | 8     | 1     | 6         | 0     | 2       | 0       | 2       | 2          | 4         | 1          | 1        | 1        | 0            | 0             | 4                    | 9                      | 0              | 0             | 0             | 0       | 1           | 86
Adelaide | Betts, Eddie      | 1986-11-26 | 174    | 74     | Forward           | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 14        | 7     | 2     | 7         | 0     | 2       | 0       | 2       | 0          | 1         | 1          | 1        | 1        | 0            | 0             | 6                    | 9                      | 0              | 1             | 3             | 0       | 1           | 85
Adelaide | Brown, Luke       | 1992-09-22 | 181    | 81     | Defender          | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 15        | 10    | 2     | 5         | 0     | 0       | 0       | 0       | 5          | 1         | 0          | 0        | 0        | 0            | 0             | 1                    | 10                     | 0              | 0             | 2             | 0       | 0           | 82
Adelaide | Crouch, Matt      | 1995-04-21 | 182    | 80     | Midfield          | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 41        | 18    | 6     | 23        | 0     | 0       | 0       | 2       | 3          | 3         | 7          | 4        | 0        | 1            | 0             | 11                   | 31                     | 0              | 0             | 0             | 0       | 1           | 80
Adelaide | Doedee, Tom       | 1997-03-01 | 188    | 88     | Defender          | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 21        | 7     | 7     | 14        | 0     | 0       | 0       | 2       | 4          | 1         | 0          | 2        | 2        | 0            | 0             | 8                    | 14                     | 0              | 0             | 9             | 1       | 0           | 93
Adelaide | Douglas, Richard  | 1987-02-06 | 181    | 79     | Midfield, Forward | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 13        | 7     | 3     | 6         | 1     | 2       | 0       | 0       | 1          | 2         | 2          | 4        | 0        | 4            | 0             | 5                    | 9                      | 0              | 0             | 2             | 2       | 0           | 84
Adelaide | Ellis-Yolmen, Cam | 1993-01-28 | 190    | 97     | Midfield          | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 17        | 7     | 5     | 10        | 1     | 0       | 0       | 1       | 2          | 3         | 6          | 2        | 0        | 0            | 0             | 11                   | 6                      | 1              | 0             | 0             | 0       | 0           | 67
Adelaide | Fogarty, Darcy    | 1999-09-25 | 193    | 94     | Forward           | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 6         | 3     | 3     | 3         | 2     | 0       | 0       | 4       | 0          | 1         | 0          | 2        | 0        | 1            | 0             | 2                    | 4                      | 1              | 1             | 0             | 0       | 0           | 83
Adelaide | Gibbs, Bryce      | 1989-03-15 | 188    | 84     | Midfield          | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 35        | 21    | 7     | 14        | 2     | 1       | 0       | 4       | 2          | 8         | 7          | 5        | 1        | 1            | 2             | 13                   | 21                     | 0              | 2             | 0             | 1       | 0           | 87
Adelaide | Greenwood, Hugh   | 1992-03-06 | 191    | 92     | Midfield          | 2018   | R1    | 2018-03-23 | 87    | -12    | L       | Essendon   | Docklands | 13        | 8     | 1     | 5         | 1     | 1       | 0       | 2       | 0          | 0         | 3          | 4        | 0        | 0            | 0             | 8                    | 3                      | 0              | 0             | 0             | 0       | 0           | 65
... (63702 rows omitted)

In [79]:
results

Rank | Team            | Games Played | Won  | Lost | Tied | Pts Scored | Pts Given  | Ratio  | Points | Year
1    | Hawthorn        | 22           | 17   | 5    | 0    | 2679       | 1733       | 154.59 | 68     | 2012
2    | Adelaide        | 22           | 17   | 5    | 0    | 2428       | 1833       | 132.46 | 68     | 2012
3    | Sydney (P)      | 22           | 16   | 6    | 0    | 2290       | 1629       | 140.58 | 64     | 2012
4    | Collingwood     | 22           | 16   | 6    | 0    | 2123       | 1823       | 116.46 | 64     | 2012
5    | West Coast      | 22           | 15   | 7    | 0    | 2244       | 1807       | 124.18 | 60     | 2012
6    | Geelong         | 22           | 15   | 7    | 0    | 2209       | 1886       | 117.13 | 60     | 2012
7    | Fremantle       | 22           | 14   | 8    | 0    | 1956       | 1691       | 115.67 | 56     | 2012
8    | North Melbourne | 22           | 14   | 8    | 0    | 2359       | 2097       | 112.49 | 56     | 2012
9    | St Kilda        | 22           | 12   | 10   | 0    | 2347       | 1903       | 123.33 | 48     | 2012
10   | Carlton         | 22           | 11   | 11   | 0    | 2079       | 1925       | 108    | 44     | 2012
... (116 rows omitted)

In [5]:
stats1 = stats.drop('D.O.B', 'Height', 'Weight', 'Date', 'Opposition', 'Venue')
stats1 #For the purposes of this midterm, stats that didn't matter such as weight, opponent, etc. were dropped

Team     | Player            | Position          | Season | Round | Score | Margin | WinLoss | Disposals | Kicks | Marks | Handballs | Goals | Behinds | Hitouts | Tackles | Rebound50s | Inside50s | Clearances | Clangers | FreesFor | FreesAgainst | BrownlowVotes | ContendedPossessions | UncontendedPossessions | ContestedMarks | MarksInside50 | OnePercenters | Bounces | GoalAssists | PercentPlayed
Adelaide | Atkins, Rory      | Midfield          | 2018   | R1    | 87    | -12    | L       | 14        | 8     | 1     | 6         | 0     | 2       | 0       | 2       | 2          | 4         | 1          | 1        | 1        | 0            | 0             | 4                    | 9                      | 0              | 0             | 0             | 0       | 1           | 86
Adelaide | Betts, Eddie      | Forward           | 2018   | R1    | 87    | -12    | L       | 14        | 7     | 2     | 7         | 0     | 2       | 0       | 2       | 0          | 1         | 1          | 1        | 1        | 0            | 0             | 6                    | 9                      | 0              | 1             | 3             | 0       | 1           | 85
Adelaide | Brown, Luke       | Defender          | 2018   | R1    | 87    | -12    | L       | 15        | 10    | 2     | 5         | 0     | 0       | 0       | 0       | 5          | 1         | 0          | 0        | 0        | 0            | 0             | 1                    | 10                     | 0              | 0             | 2             | 0       | 0           | 82
Adelaide | Crouch, Matt      | Midfield          | 2018   | R1    | 87    | -12    | L       | 41        | 18    | 6     | 23        | 0     | 0       | 0       | 2       | 3          | 3         | 7          | 4        | 0        | 1            | 0             | 11                   | 31                     | 0              | 0             | 0             | 0       | 1           | 80
Adelaide | Doedee, Tom       | Defender          | 2018   | R1    | 87    | -12    | L       | 21        | 7     | 7     | 14        | 0     | 0       | 0       | 2       | 4          | 1         | 0          | 2        | 2        | 0            | 0             | 8                    | 14                     | 0              | 0             | 9             | 1       | 0           | 93
Adelaide | Douglas, Richard  | Midfield, Forward | 2018   | R1    | 87    | -12    | L       | 13        | 7     | 3     | 6         | 1     | 2       | 0       | 0       | 1          | 2         | 2          | 4        | 0        | 4            | 0             | 5                    | 9                      | 0              | 0             | 2             | 2       | 0           | 84
Adelaide | Ellis-Yolmen, Cam | Midfield          | 2018   | R1    | 87    | -12    | L       | 17        | 7     | 5     | 10        | 1     | 0       | 0       | 1       | 2          | 3         | 6          | 2        | 0        | 0            | 0             | 11                   | 6                      | 1              | 0             | 0             | 0       | 0           | 67
Adelaide | Fogarty, Darcy    | Forward           | 2018   | R1    | 87    | -12    | L       | 6         | 3     | 3     | 3         | 2     | 0       | 0       | 4       | 0          | 1         | 0          | 2        | 0        | 1            | 0             | 2                    | 4                      | 1              | 1             | 0             | 0       | 0           | 83
Adelaide | Gibbs, Bryce      | Midfield          | 2018   | R1    | 87    | -12    | L       | 35        | 21    | 7     | 14        | 2     | 1       | 0       | 4       | 2          | 8         | 7          | 5        | 1        | 1            | 2             | 13                   | 21                     | 0              | 2             | 0             | 1       | 0           | 87
Adelaide | Greenwood, Hugh   | Midfield          | 2018   | R1    | 87    | -12    | L       | 13        | 8     | 1     | 5         | 1     | 1       | 0       | 2       | 0          | 0         | 3          | 4        | 0        | 0            | 0             | 8                    | 3                      | 0              | 0             | 0             | 0       | 0           | 65
... (63702 rows omitted)

In [6]:
results = results.drop('Notes') #Got rid of 'Notes' column because it was full of NaNs
results

Rank | Team            | Games Played | Won  | Lost | Tied | Pts Scored | Pts Given  | Ratio  | Points | Year
1    | Hawthorn        | 22           | 17   | 5    | 0    | 2679       | 1733       | 154.59 | 68     | 2012
2    | Adelaide        | 22           | 17   | 5    | 0    | 2428       | 1833       | 132.46 | 68     | 2012
3    | Sydney (P)      | 22           | 16   | 6    | 0    | 2290       | 1629       | 140.58 | 64     | 2012
4    | Collingwood     | 22           | 16   | 6    | 0    | 2123       | 1823       | 116.46 | 64     | 2012
5    | West Coast      | 22           | 15   | 7    | 0    | 2244       | 1807       | 124.18 | 60     | 2012
6    | Geelong         | 22           | 15   | 7    | 0    | 2209       | 1886       | 117.13 | 60     | 2012
7    | Fremantle       | 22           | 14   | 8    | 0    | 1956       | 1691       | 115.67 | 56     | 2012
8    | North Melbourne | 22           | 14   | 8    | 0    | 2359       | 2097       | 112.49 | 56     | 2012
9    | St Kilda        | 22           | 12   | 10   | 0    | 2347       | 1903       | 123.33 | 48     | 2012
10   | Carlton         | 22           | 11   | 11   | 0    | 2079       | 1925       | 108    | 44     | 2012
... (116 rows omitted)

In [7]:
#Part 3:

#1) Write (Python) code to generate annual summary statistics per team – regular season only

#First, we are creating a column known as 'Team and Year' that will help us combine the two tables and group into team stats
stats_season_list = [str(x) for x in stats1.column('Season')] 
stats_team_list = [x for x in stats1.column('Team')]
stats_team_year = make_array() 
for i in range(len(stats_season_list)): #This step takes a bit long to run so please be patient
    temp1 = stats_team_list[i] + ' '+ stats_season_list[i]
    stats_team_year = np.append(stats_team_year, temp1)

#Now we do the same for 'results'
results_year_list = [str(x) for x in results.column('Year')]
results_team_list = [x for x in results.column('Team')]
results_team_year = make_array()
for i in range(len(results_year_list)):
    temp2 = results_team_list[i] + ' ' + results_year_list[i]
    results_team_year = np.append(results_team_year, temp2)

In [8]:
#Adding the column to 'regular_season_stats'
with_team_year = stats1.with_column('Team and Year', stats_team_year)
regular_season_stats = with_team_year.where('Round', are.containing('R')) #we isolate the stats from the regular season
annual_team_stats = regular_season_stats.drop('Team', 'Round', 'Player', 'Position', 'Season', 'Score', 'Margin', 'WinLoss').group('Team and Year', np.sum)
annual_team_stats

Team and Year       | Disposals sum | Kicks sum | Marks sum | Handballs sum | Goals sum | Behinds sum | Hitouts sum | Tackles sum | Rebound50s sum | Inside50s sum | Clearances sum | Clangers sum | FreesFor sum | FreesAgainst sum | BrownlowVotes sum | ContendedPossessions sum | UncontendedPossessions sum | ContestedMarks sum | MarksInside50 sum | OnePercenters sum | Bounces sum | GoalAssists sum | PercentPlayed sum
Adelaide 2012       | 7709          | 4793      | 1969      | 2916          | 357       | 239         | 981         | 1304        | 736            | 1163          | 911            | 944          | 373          | 397              | 88                | 3316                     | 4341                       | 283                | 304               | 1032              | 129         | 249             | 39599
Adelaide 2013       | 8092          | 4780      | 2085      | 3312          | 297       | 225         | 854         | 1286        | 743            | 1170          | 811            | 958          | 425          | 388              | 65                | 3184                     | 4831                       | 233                | 246               | 922               | 214         | 193             | 39601
Adelaide 2014       | 8070          | 4562      | 1872      | 3508          | 315       | 225         | 886         | 1366        | 776            | 1212          | 862            | 928          | 371          | 319              | 71                | 3189                     | 4804                       | 247                | 242               | 1109              | 254         | 209             | 39598
Adelaide 2015       | 7590          | 4508      | 1926      | 3082          | 308       | 197         | 912         | 1275        | 727            | 1167          | 864            | 1040         | 341          | 356              | 73                | 3005                     | 4518                       | 231                | 288               | 887               | 134         | 228             | 37815
Adelaide 2016       | 8659          | 4858      | 2097      | 3801          | 363       | 249         | 841         | 1517        | 749            | 1265          | 840            | 1105         | 412          | 381              | 87                | 3366                     | 5315                       | 275                | 316               | 1038              | 151         | 264             | 39605
Adelaide 2017       | 8740          | 4802      | 1969      | 3938          | 354       | 230         | 1003        | 1575        | 754            | 1284          | 867            | 1231         | 436          | 434              | 88                | 3428                     | 5349                       | 281                | 329               | 1103              | 148         | 248             | 39602
Adelaide 2018       | 8425          | 4918      | 2014      | 3507          | 279       | 214         | 904         | 1422        | 808            | 1162          | 823            | 1084         | 425          | 377              | 69                | 3378                     | 5014                       | 253                | 208               | 1038              | 116         | 182             | 39606
Brisbane Lions 2012 | 7716          | 4403      | 1890      | 3313          | 279       | 185         | 749         | 1393        | 817            | 1048          | 808            | 1097         | 398          | 446              | 55                | 3086                     | 4595                       | 204                | 218               | 1230              | 116         | 172             | 39598
Brisbane Lions 2013 | 7540          | 4336      | 1819      | 3204          | 276       | 207         | 836         | 1398        | 782            | 1117          | 785            | 1042         | 395          | 460              | 64                | 2972                     | 4487                       | 220                | 222               | 1062              | 206         | 194             | 39588
Brisbane Lions 2014 | 7669          | 4163      | 1882      | 3506          | 221       | 148         | 840         | 1405        | 780            | 1002          | 808            | 965          | 382          | 395              | 42                | 2749                     | 4835                       | 162                | 185               | 1166              | 166         | 149             | 39610
... (116 rows omitted)

In [9]:
#Now we can join together the stats with the results:
question_one = results.with_column('Team and Year', results_team_year).join('Team and Year', annual_team_stats).drop('Team', 'Year')
question_one

Team and Year       | Rank | Games Played | Won  | Lost | Tied | Pts Scored | Pts Given  | Ratio  | Points | Disposals sum | Kicks sum | Marks sum | Handballs sum | Goals sum | Behinds sum | Hitouts sum | Tackles sum | Rebound50s sum | Inside50s sum | Clearances sum | Clangers sum | FreesFor sum | FreesAgainst sum | BrownlowVotes sum | ContendedPossessions sum | UncontendedPossessions sum | ContestedMarks sum | MarksInside50 sum | OnePercenters sum | Bounces sum | GoalAssists sum | PercentPlayed sum
Adelaide 2012       | 2    | 22           | 17   | 5    | 0    | 2428       | 1833       | 132.46 | 68     | 7709          | 4793      | 1969      | 2916          | 357       | 239         | 981         | 1304        | 736            | 1163          | 911            | 944          | 373          | 397              | 88                | 3316                     | 4341                       | 283                | 304               | 1032              | 129         | 249             | 39599
Adelaide 2013       | 11   | 22           | 10   | 12   | 0    | 2064       | 1909       | 108.12 | 40     | 8092          | 4780      | 2085      | 3312          | 297       | 225         | 854         | 1286        | 743            | 1170          | 811            | 958          | 425          | 388              | 65                | 3184                     | 4831                       | 233                | 246               | 922               | 214         | 193             | 39601
Adelaide 2014       | 10   | 22           | 11   | 11   | 0    | 2175       | 1907       | 114.1  | 44     | 8070          | 4562      | 1872      | 3508          | 315       | 225         | 886         | 1366        | 776            | 1212          | 862            | 928          | 371          | 319              | 71                | 3189                     | 4804                       | 247                | 242               | 1109              | 254         | 209             | 39598
Adelaide 2015       | 7    | 21           | 13   | 8    | 0    | 2107       | 1821       | 115.7  | 54     | 7590          | 4508      | 1926      | 3082          | 308       | 197         | 912         | 1275        | 727            | 1167          | 864            | 1040         | 341          | 356              | 73                | 3005                     | 4518                       | 231                | 288               | 887               | 134         | 228             | 37815
Adelaide 2016       | 5    | 22           | 16   | 6    | 0    | 2483       | 1795       | 138.3  | 64     | 8659          | 4858      | 2097      | 3801          | 363       | 249         | 841         | 1517        | 749            | 1265          | 840            | 1105         | 412          | 381              | 87                | 3366                     | 5315                       | 275                | 316               | 1038              | 151         | 264             | 39605
Adelaide 2017       | 1    | 22           | 15   | 6    | 1    | 2415       | 1776       | 136    | 62     | 8740          | 4802      | 1969      | 3938          | 354       | 230         | 1003        | 1575        | 754            | 1284          | 867            | 1231         | 436          | 434              | 88                | 3428                     | 5349                       | 281                | 329               | 1103              | 148         | 248             | 39602
Adelaide 2018       | 12   | 22           | 12   | 10   | 0    | 1941       | 1865       | 104.1  | 48     | 8425          | 4918      | 2014      | 3507          | 279       | 214         | 904         | 1422        | 808            | 1162          | 823            | 1084         | 425          | 377              | 69                | 3378                     | 5014                       | 253                | 208               | 1038              | 116         | 182             | 39606
Brisbane Lions 2012 | 13   | 22           | 10   | 12   | 0    | 1904       | 2092       | 91.01  | 40     | 7716          | 4403      | 1890      | 3313          | 279       | 185         | 749         | 1393        | 817            | 1048          | 808            | 1097         | 398          | 446              | 55                | 3086                     | 4595                       | 204                | 218               | 1230              | 116         | 172             | 39598
Brisbane Lions 2013 | 12   | 22           | 10   | 12   | 0    | 1922       | 2144       | 89.65  | 40     | 7540          | 4336      | 1819      | 3204          | 276       | 207         | 836         | 1398        | 782            | 1117          | 785            | 1042         | 395          | 460              | 64                | 2972                     | 4487                       | 220                | 222               | 1062              | 206         | 194             | 39588
Brisbane Lions 2014 | 15   | 22           | 7    | 15   | 0    | 1532       | 2212       | 69.3   | 28     | 7669          | 4163      | 1882      | 3506          | 221       | 148         | 840         | 1405        | 780            | 1002          | 808            | 965          | 382          | 395              | 42                | 2749                     | 4835                       | 162                | 185               | 1166              | 166         | 149             | 39610
... (109 rows omitted)

In [13]:
#2) Write code to generate annual summary statistics per player – regular season only
#As part of the previous question, we created a table called 'regular_season_stats' that isolates the regular season 
#We will create a column called 'Player and Year', similar to 'Team and Year' to help us group the stats together

player_list = [x for x in regular_season_stats.column('Player')]
season_list = [str(x) for x in regular_season_stats.column('Season')]
player_seasons = make_array()
for i in range(len(player_list)): #Again, this takes a little while (sorry)
    temp = player_list[i]+ ' ' + season_list[i]
    player_seasons = np.append(player_seasons, temp)

In [21]:
#Went to another cell so that I don't have to run the long code every time
#Adding the column
with_player_seasons = regular_season_stats.with_column('Player and Year', player_seasons)
question_two = with_player_seasons.group('Player and Year', np.sum).drop('Team sum', 'Round sum','Player sum', 'Position sum', 'Season sum')
question_two

Player and Year   | Score sum | Margin sum | WinLoss sum | Disposals sum | Kicks sum | Marks sum | Handballs sum | Goals sum | Behinds sum | Hitouts sum | Tackles sum | Rebound50s sum | Inside50s sum | Clearances sum | Clangers sum | FreesFor sum | FreesAgainst sum | BrownlowVotes sum | ContendedPossessions sum | UncontendedPossessions sum | ContestedMarks sum | MarksInside50 sum | OnePercenters sum | Bounces sum | GoalAssists sum | PercentPlayed sum | Team and Year sum
Abbott, Ryan 2018 | 382       | 232        |             | 38            | 17        | 9         | 21            | 3         | 2           | 82          | 18          | 2              | 2             | 8              | 10           | 2            | 6                | 0                 | 20                       | 20                         | 1                  | 5                 | 13                | 0           | 1               | 253               |
Ablett, Gary 2012 | 1329      | -931       |             | 675           | 389       | 61        | 286           | 26        | 19          | 0           | 110         | 61             | 101           | 132            | 81           | 41           | 28               | 24                | 298                      | 368                        | 14                 | 13                | 32                | 31          | 19              | 1849              |
Ablett, Gary 2013 | 1835      | -140       |             | 655           | 343       | 73        | 312           | 28        | 23          | 0           | 96          | 39             | 113           | 124            | 73           | 35           | 25               | 28                | 313                      | 333                        | 9                  | 12                | 17                | 25          | 17              | 1977              |
Ablett, Gary 2014 | 1385      | 20         |             | 481           | 254       | 30        | 227           | 24        | 7           | 0           | 91          | 38             | 77            | 118            | 63           | 35           | 23               | 22                | 262                      | 211                        | 3                  | 4                 | 19                | 10          | 19              | 1358              |
Ablett, Gary 2015 | 522       | -81        |             | 137           | 94        | 12        | 43            | 10        | 3           | 0           | 28          | 16             | 27            | 37             | 18           | 15           | 9                | 5                 | 66                       | 67                         | 1                  | 2                 | 9                 | 1           | 4               | 455               |
Ablett, Gary 2016 | 1210      | -286       |             | 378           | 203       | 28        | 175           | 10        | 12          | 0           | 85          | 37             | 61            | 103            | 42           | 19           | 19               | 6                 | 185                      | 190                        | 0                  | 6                 | 17                | 12          | 5               | 1225              |
Ablett, Gary 2017 | 1264      | -129       |             | 462           | 266       | 49        | 196           | 8         | 11          | 0           | 77          | 35             | 82            | 107            | 65           | 13           | 18               | 14                | 192                      | 256                        | 2                  | 3                 | 9                 | 8           | 12              | 1209              |
Ablett, Gary 2018 | 1696      | 366        |             | 525           | 280       | 79        | 245           | 16        | 14          | 0           | 66          | 36             | 90            | 82             | 77           | 24           | 31               | 14                | 199                      | 329                        | 2                  | 6                 | 14                | 9           | 8               | 1477              |
Acres, Blake 2014 | 186       | -215       |             | 26            | 11        | 3         | 15            | 1         | 0           | 0           | 8           | 3              | 2             | 6              | 2            | 1            | 0                | 0                 | 18                       | 11                         | 0                  | 0                 | 4                 | 0           | 0               | 150               |
Acres, Blake 2015 | 562       | -168       |             | 83            | 44        | 18        | 39            | 0         | 1           | 10          | 18          | 4              | 17            | 10             | 11           | 2            | 6                | 0                 | 34                       | 52                         | 4                  | 1                 | 7                 | 0           | 2               | 394               |
... (4639 rows omitted)

In [50]:
#3) Write code to help determine which players contributed the most to each team on a position-wise basis - regular season only
#For me, a player's contribution is best measured by the amounts of points he scored, except for defenders and rucks.

#For this, I decided it was easier to make a function which would return the relevant stats for each position for each team, 
#sorting them from most time played to lowest

with_points = stats1.where('Round', are.containing('R')).with_column('Points', (6*regular_season_stats.column('Goals'))+regular_season_stats.column('Behinds'))

def contribution(team, position, year):
    #isolated to specific position, team, and year
    specific = with_points.where('Position', are.containing(position)).where('Team', team).where('Season', year)
    if position == 'Forward': #picking relevant stats for each position
        relevant_stats = specific.select('Player', 'Points', 'Disposals', 'Marks', 'Goals', 'Behinds', 'Inside50s', 'FreesFor', 'BrownlowVotes')
    if position == 'Midfield':
        relevant_stats = specific.select('Player', 'Points', 'Disposals', 'Marks', 'Goals', 'Behinds', 'Tackles', 'GoalAssists','BrownlowVotes')
    if position == 'Ruck':
        relevant_stats = specific.select('Player', 'Points', 'Disposals', 'Marks', 'Hitouts', 'Tackles', 'Clangers', 'OnePercenters', 'BrownlowVotes')
    if position == 'Defender':
        relevant_stats = specific.select('Player', 'Points', 'Tackles', 'Clangers', 'OnePercenters', 'BrownlowVotes')
    #averages out the percent of the game played per player
    percent_played = specific.select('Player', 'PercentPlayed').group('Player', np.average)
    #sums up other stats:
    total_position_stats = relevant_stats.group('Player', np.sum)
    #finds percent of points scored in a season for a player
    percent_score = 100*(total_position_stats.column('Points sum')/results.where('Team', team).where('Year', year).column('Pts Scored').item(0))
    #combines everything together
    question_three = percent_played.with_column('Percent of Team Score', percent_score).join('Player', total_position_stats)
    return question_three.sort('PercentPlayed average', descending = True) #sorts by Percent Played

#This shows that the biggest contributer at Forward for Adelaide in 2018 was Josh Jenkins
contribution('Adelaide', 'Forward', 2018)

Player              | PercentPlayed average | Percent of Team Score | Points sum | Disposals sum | Marks sum | Goals sum | Behinds sum | Inside50s sum | FreesFor sum | BrownlowVotes sum
Jenkins, Josh       | 90.3182               | 15.6105               | 303        | 283           | 111       | 46        | 27          | 57            | 28           | 3
Lynch, Tom T        | 84.1765               | 5.35806               | 104        | 332           | 97        | 16        | 8           | 44            | 12           | 0
Himmelberg, Elliott | 84                    | 0.360639              | 7          | 13            | 5         | 1         | 1           | 2             | 0            | 0
McGovern, Mitch     | 83.75                 | 5.30654               | 103        | 155           | 78        | 15        | 13          | 32            | 15           | 2
Betts, Eddie        | 82.7778               | 9.99485               | 194        | 239           | 43        | 29        | 20          | 39            | 12           | 1
Knight, Riley       | 81                    | 2.36991               | 46         | 120           | 24        | 7         | 4           | 17            | 10           | 0
Douglas, Richard    | 80.8824               | 4.9459                | 96         | 313           | 59        | 14        | 12          | 55            | 20           | 3
Gallucci, Jordan    | 80.375                | 5.2035                | 101        | 186           | 42        | 15        | 11          | 48            | 11           | 0
Fogarty, Darcy      | 80.2                  | 2.93663               | 57         | 84            | 32        | 9         | 3           | 20            | 7            | 0
Walker, Taylor      | 79.4286               | 8.91293               | 173        | 161           | 59        | 26        | 17          | 41            | 16           | 5
... (2 rows omitted)

In [29]:
#4) Write code to help determine which players/teams had the most playoff success.
#For me, playoff success can be quantified in two ways, playoff wins and championships
#Let's start with championships
#Here, we are making a table that contains every championship team
champs = stats1.where('Round', are.equal_to('GF')).where('WinLoss', are.equal_to('W'))
champ_player_numbers = champs.group('Team')
champ_count = champ_player_numbers.with_column('Championships', champ_player_numbers.column('count')/22).drop('count')
champ_count #From this, we see that Hawthorn has dominated by winning three of the seven Grand Finals, nearly half!

Team             | Championships
Hawthorn         | 3
Richmond         | 1
Sydney           | 1
West Coast       | 1
Western Bulldogs | 1

In [30]:
#We can do something similar to determine which PLAYERS have won the most championships
champ_players = champs.group('Player')
champ_players.sort('count', descending = True) #Here we see that all these players won three championships, meaning they are all
                                               #probably on Hawthorne

Player           | count
Stratton, Ben    | 3
Smith, Isaac     | 3
Shiels, Liam     | 3
Roughead, Jarryd | 3
Rioli, Cyril     | 3
Puopolo, Paul    | 3
Mitchell, Sam    | 3
Lewis, Jordan    | 3
Lake, Brian      | 3
Hodge, Luke      | 3
... (106 rows omitted)

In [40]:
#Next, let's see which teams have won the most playoff matches
playoff_wins = stats1.where('Round', are.containing('F')).where('WinLoss', 'W')
players_per_win = playoff_wins.group('Team')
playoff_wins_per_team = players_per_win.with_column('Playoff Wins', players_per_win.column('count')/22).drop('count')
playoff_wins_per_team.sort('Playoff Wins', descending = True) #Once again, we see that Hawthorne has been dominant

Team                   | Playoff Wins
Hawthorn               | 11
Sydney                 | 9
West Coast             | 6
Adelaide               | 5
Western Bulldogs       | 4
Richmond               | 4
North Melbourne        | 4
Fremantle              | 4
Port Adelaide          | 3
Greater Western Sydney | 3
... (4 rows omitted)

In [43]:
#Once again, we can use a similar method to see which players have won the most playoff games
wins_per_player = playoff_wins.group('Player')
wins_per_player.sort('count', descending = True)
#Here we see that Sam Mitchell has won more playoff games than anyone else in AFL history
#The other table reveals that he has three championships as well

Player           | count
Mitchell, Sam    | 12
Stratton, Ben    | 11
Smith, Isaac     | 11
Shiels, Liam     | 11
Roughead, Jarryd | 11
Puopolo, Paul    | 11
Lewis, Jordan    | 11
Hale, David      | 11
Gibson, Josh     | 11
Burgoyne, Shaun  | 11
... (427 rows omitted)

In [48]:
#5) Develop your own assessment method of player performance by position and write code to rank players by position by year 
#   on that basis.

#For this question, I think the contributions() function I wrote for question three ranks players well based off of their team,
# so I decided to implement something similar.

def position_ranks(position, year):
    specific = with_points.where('Position', are.containing(position)).where('Season', year)
    if position == 'Forward': #picking relevant stats for each position
        relevant_stats = specific.select('Player', 'Points', 'Disposals', 'Marks', 'Goals', 'Behinds', 'Inside50s', 'FreesFor', 'BrownlowVotes')
    if position == 'Midfield':
        relevant_stats = specific.select('Player', 'Points', 'Disposals', 'Marks', 'Goals', 'Behinds', 'Tackles', 'GoalAssists','BrownlowVotes')
    if position == 'Ruck':
        relevant_stats = specific.select('Player', 'Points', 'Disposals', 'Marks', 'Hitouts', 'Tackles', 'Clangers', 'OnePercenters', 'BrownlowVotes')
    if position == 'Defender':
        relevant_stats = specific.select('Player', 'Points', 'Tackles', 'Clangers', 'OnePercenters', 'BrownlowVotes')
    percent_played = specific.select('Player', 'PercentPlayed').group('Player', np.average)
    total_position_stats = relevant_stats.group('Player', np.sum)
    question_five = percent_played.join('Player', total_position_stats).sort('BrownlowVotes sum', descending = True)
    return question_five #This time, I decided to rank the players by the number of Brownlow Medal votes they received
                         # as the award is a good indication of who was the best player.

position_ranks('Forward', 2018)

Player               | PercentPlayed average | Points sum | Disposals sum | Marks sum | Goals sum | Behinds sum | Inside50s sum | FreesFor sum | BrownlowVotes sum
Dangerfield, Patrick | 84.0476               | 166        | 594           | 78        | 24        | 22          | 107           | 55           | 17
Franklin, Lance      | 92.6667               | 384        | 280           | 125       | 57        | 42          | 89            | 27           | 16
Kelly, Tim           | 83.9545               | 152        | 508           | 73        | 23        | 14          | 85            | 19           | 13
de Goey, Jordan      | 80.8235               | 232        | 290           | 72        | 36        | 16          | 65            | 14           | 12
Lambert, Kane        | 85.15                 | 100        | 451           | 75        | 15        | 10          | 76            | 10           | 12
Smith, Devon         | 83.6364               | 118        | 484           | 83        | 17        | 16          | 69            | 25           | 11
Darling, Jack        | 83.0556               | 275        | 234           | 110       | 42        | 23          | 42            | 21           | 11
Riewoldt, Jack       | 92.7727               | 423        | 312           | 137       | 65        | 33          | 71            | 26           | 10
Gunston, Jack        | 89.381                | 315        | 375           | 114       | 48        | 27          | 65            | 21           | 10
Hawkins, Tom         | 91.4                  | 377        | 314           | 146       | 58        | 29          | 40            | 22           | 9
... (249 rows omitted)

In [65]:
#Part 4: The answers are on the narrative, this space is just used by myself for research
wins = results.select('Team', 'Games Played', 'Pts Scored', 'Won', 'Lost', 'Points').group('Team', np.sum)
q1 = wins.with_column('Points per Game', wins.column('Points sum')/wins.column('Games Played sum')).with_column('Score per Game', wins.column('Pts Scored sum')/wins.column('Games Played sum'))
q1.sort('Points per Game', descending = True)

Team                 | Games Played sum | Pts Scored sum | Won sum | Lost sum | Points sum | Points per Game | Score per Game
Hawthorn (P)         | 66               | 7433           | 52      | 14       | 208        | 3.15152         | 112.621
West Coast (P)       | 22               | 2012           | 16      | 6        | 64         | 2.90909         | 91.4545
Sydney (P)           | 22               | 2290           | 16      | 6        | 64         | 2.90909         | 104.091
Sydney               | 132              | 12512          | 93      | 38       | 374        | 2.83333         | 94.7879
Geelong              | 153              | 14918          | 106     | 45       | 430        | 2.81046         | 97.5033
Western Bulldogs (P) | 22               | 1857           | 15      | 7        | 60         | 2.72727         | 84.4091
Richmond (P)         | 22               | 1992           | 15      | 7        | 60         | 2.72727         | 90.5455
Hawthorn             | 88               | 8649           | 59      | 28       | 238        | 2.70455         | 98.2841
Adelaide             | 153              | 15613          | 94      | 58       | 380        | 2.48366         | 102.046
West Coast           | 132              | 12802          | 79      | 52       | 318        | 2.40909         | 96.9848
... (13 rows omitted)

In [62]:
averages = stats1.group('Team', np.average).drop('Player average', 'Position average', 'Season average', 'Round average', 'WinLoss average')
averages.sort('Disposals average', descending = True)

Team                   | Score average | Margin average | Disposals average | Kicks average | Marks average | Handballs average | Goals average | Behinds average | Hitouts average | Tackles average | Rebound50s average | Inside50s average | Clearances average | Clangers average | FreesFor average | FreesAgainst average | BrownlowVotes average | ContendedPossessions average | UncontendedPossessions average | ContestedMarks average | MarksInside50 average | OnePercenters average | Bounces average | GoalAssists average | PercentPlayed average
Hawthorn               | 103.62        | 23.0058        | 17.3955           | 9.9362        | 4.33865       | 7.45933           | 0.694046      | 0.444444        | 1.91042         | 3.04918         | 1.41653            | 2.49176           | 1.75332            | 2.09649          | 0.830675         | 0.821372             | 0.153376              | 6.31712                      | 11.0245                        | 0.452685               | 0.584264              | 2.43939               | 0.350877        | 0.475811            | 81.7881
Western Bulldogs       | 82.566        | -8.74843       | 17.2945           | 9.22556       | 3.82047       | 8.0689            | 0.540309      | 0.407662        | 1.69325         | 3.03974         | 1.50029            | 2.37164           | 1.74728            | 2.09548          | 0.862207         | 0.800457             | 0.11721               | 6.54717                      | 10.6895                        | 0.465123               | 0.477987              | 2.15952               | 0.379931        | 0.359062            | 81.7996
Collingwood            | nan           | nan            | 17.2298           | 9.67817       | 4.19108       | 7.55163           | 0.588384      | 0.424523        | 1.73345         | 3.17116         | 1.5376             | 2.4046            | 1.67172            | 2.2096           | 0.821268         | 0.758137             | 0.147868              | 6.54405                      | 10.6759                        | 0.501403               | 0.560045              | 2.19529               | 0.406846        | 0.409371            | 81.8109
Essendon               | 85.1603       | -6.85897       | 17.2267           | 9.82284       | 4.53059       | 7.40385           | 0.556527      | 0.427156        | 1.71474         | 2.91987         | 1.62354            | 2.36043           | 1.63666            | 2.21562          | 0.807401         | 0.818473             | 0.120338              | 6.29225                      | 10.9143                        | 0.513695               | 0.518648              | 2.10286               | 0.332751        | 0.379953            | 81.8351
Sydney                 | 94.2558       | 20.9767        | 17.1948           | 9.46485       | 3.77484       | 7.72992           | 0.627114      | 0.42204         | 1.83853         | 3.26348         | 1.71644            | 2.45111           | 1.7648             | 2.25819          | 0.824524         | 0.862051             | 0.17019               | 6.824                        | 10.254                         | 0.51982                | 0.531977              | 2.2315                | 0.288848        | 0.423626            | 81.7955
Adelaide               | 101.233       | 16.5092        | 16.9626           | 9.8483        | 4.14306       | 7.11433           | 0.669827      | 0.465421        | 1.89822         | 2.89013         | 1.57223            | 2.49303           | 1.7705             | 2.17708          | 0.830731         | 0.790017             | 0.150864              | 6.76743                      | 10.1252                        | 0.53681                | 0.571668              | 2.13162               | 0.34077         | 0.46068             | 81.8179
Geelong                | nan           | nan            | 16.8871           | 9.33168       | 4.18678       | 7.55537           | 0.63416       | 0.44022         | 1.70579         | 3.17052         | 1.47273            | 2.45923           | 1.63085            | 2.23361          | 0.873003         | 0.887879             | 0.156749              | 6.52314                      | 10.405                         | 0.569146               | 0.606887              | 2.08402               | 0.278237        | 0.439945            | 81.8129
St Kilda               | 82.8377       | -13.0909       | 16.7969           | 9.37161       | 4.2562        | 7.42532           | 0.540437      | 0.428571        | 1.61541         | 2.94215         | 1.58589            | 2.28571           | 1.59829            | 2.23642          | 0.7866           | 0.840024             | 0.107143              | 6.08589                      | 10.7202                        | 0.486423               | 0.553129              | 1.99793               | 0.489669        | 0.373967            | 81.8037
Richmond               | 90.7531       | 9.62346        | 16.7264           | 9.59624       | 4.12486       | 7.13019           | 0.59624       | 0.430415        | 1.64478         | 2.80527         | 1.54602            | 2.4046            | 1.66105            | 2.29153          | 0.876263         | 0.899832             | 0.150673              | 6.40039                      | 10.2256                        | 0.501684               | 0.583614              | 2.14478               | 0.429854        | 0.402918            | 81.7935
Greater Western Sydney | 82.9627       | -13.7826       | 16.5954           | 9.35093       | 4.01073       | 7.24449           | 0.543478      | 0.405985        | 1.83794         | 2.98842         | 1.72219            | 2.22388           | 1.76595            | 2.31084          | 0.838227         | 0.896386             | 0.112084              | 6.26398                      | 10.2535                        | 0.446358               | 0.457651              | 2.11886               | 0.502541        | 0.370695            | 81.8123
... (8 rows omitted)

In [69]:
positions = stats1.select('Player', 'Position', 'BrownlowVotes')

In [77]:
positions.where('Position', are.containing('Defen')).drop('Position').group('Player', np.sum).sort('BrownlowVotes sum', descending = True)

Player          | BrownlowVotes sum
Hodge, Luke     | 45
Montagna, Leigh | 44
Simpson, Kade   | 41
Lewis, Jordan   | 41
Laird, Rory     | 41
Taylor, Harry   | 36
Vince, Bernie   | 32
Boyd, Matthew   | 32
Rance, Alex     | 31
McVeigh, Jarrad | 29
... (442 rows omitted)